version: 0.1
ecr:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-api-ecr
      s3_prefix: udp-api-ecr
      region: us-east-1
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "RepositoryName=test-ecr-repo"

network:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-api-networking
      s3_prefix: udp-api-networking
      region: us-east-1
      capabilities: CAPABILITY_IAM

ecs:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-api-ecs
      s3_prefix: udp-api-ecs
      region: us-east-1
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "NetworkStackName=udp-api-networking"
        - "ECRStackName=udp-api-ecr"
        - "ECRRepositoryUrl=965116670064.dkr.ecr.us-east-1.amazonaws.com/test-ecr-repo"
        - "DockerImageTag=latest"
