version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-service
      resolve_s3: true
      s3_prefix: udp-service
      region: us-east-1
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "DockerImageName=hello-world"
        - "DockerImageTag=latest"

ecr:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-service-ecr
      resolve_s3: true
      s3_prefix: udp-service-ecr
      region: us-east-1
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "RepositoryName=andmoredev-test-repo"

network:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-service-networking
      resolve_s3: true
      s3_prefix: udp-service-networking
      region: us-east-1
      capabilities: CAPABILITY_IAM

ecs:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

  deploy:
    parameters:
      stack_name: udp-service-ecs
      resolve_s3: true
      s3_prefix: udp-service-ecs
      region: us-east-1
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "NetworkStackName=udp-service-networking"
        - "ECRRepositoryUrl=965116670064.dkr.ecr.us-east-1.amazonaws.com/andmoredev-test-repo"
        - "DockerImageTag=latest"
