name: Network Template Deployment

on:
  push:
    paths:
      - template-network.yaml
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-network:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
        role-session-name: network-repo-deploy
        role-duration-seconds: 3600
        role-skip-session-tagging: true

    - name: Build and deploy Network template
      run: |
        sam build  \
          --template template-network.yaml \
          --config-file samconfig.yaml \
          --config-env network

        sam deploy \
          --template template-network.yaml \
          --config-file samconfig.yaml \
          --config-env network \
          --s3-bucket ${{ secrets.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}